### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by cloud-tribal** [flyingsparx/NodeDirectUploader#13]
Everything works up until the actual sending of the file, where I get a 403 on the PUT request.

I verified all access ids and keys, request signatures, etc.

What code should I post to get help debugging ?

**Comment by willwebberley** [comment]
Hi, I know that some people have reported issues with regions causing 403 errors. Could you try setting your region explicitly to see if that fixes it? E.g.: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html.

Also, I know you said you verified everything already, but have a quick double check directly using the AWS command-line tools. E.g. `aws s3 cp /path/to/local/file s3://bucket/path` with the same credentials/bucket combo as you do in your app.

**Comment by cloud-tribal** [comment]
Ok got it to work. Turns out I was using an http library that didn't infer the Content-Type header. So I had to implement that.
