### ISSUE TITLE
Cross Origin and Region set up

### ISSUE THREAD

**Issue by kaiserbear** [flyingsparx/NodeDirectUploader#18]
Hi, I've been trying to troubleshoot an issue for about a week now. I've followed the guide, I'm happy to provide examples of code. 

I'm getting Cross Origin 403 errors when I publish to heroku (I have a pipeline with a staging and production app). 

I'm based in London, UK - and when uploading locally to a bucket (bucket region is set to London, UK) the code works as expected. I notice that when I switch to a bucket with a different EU region that the code stops working locally, leading me to assume that the issue is that regions between the bucket and the app have to be the same?

I set the regions of both (heroku)) apps to 'EU'. After some googling, I've seen a post that says that Heroku's EU servers are in the region 'eu-west-1' (Ireland). I've tried setting up all 4 EU regions of S3 bucket and publishing to heroku and getting the same error. 

Can someone let me know if I'm on the right track? fom Heroku: "A single bucket typically stores the files, assets and uploads for an application. To create a bucket access the S3 section of the AWS Management Console and create a new bucket in the US Standard region." 

Logically this wouldn't make sense to me if the app is hosted in the EU region. 

Jay

**Comment by willwebberley** [comment]
Hi there,

Some people do tend to have varying success with this, in which it works fine for some region combinations and not others! One such issue thread we had was [this one](https://github.com/flyingsparx/NodeDirectUploader/issues/11), and so it may be worth having a quick look through that (and any other closed issues on this repo) to see if they can help out at all.

As far as I know, it should not make a difference if your app is hosted in a different region to your target bucket, but your buckets will need to be configured correctly to receive the uploads (for example, double-check that CORS and other settings are correctly configured on your eu-west-1 bucket as they are on your London one). The JavaScript `aws` package is responsible for generating the signature, which should be fine as long as the region and bucket name is correctly specified in your environment/code.

**Comment by kaiserbear** [comment]
Hi Will,

thanks so much for your email. The error messaging from AWS is so generic that I’ve ended up down a rabbit hole with my investigation. 

So your email has helped me! Because I had aws.config.region = 'eu-west-2’;  simply in the wrong place. Which is a bit of a school boy error as it needs to come after creating the new AWS object.

HAZAR! I’m very happy. Cheers for replying. 

Jay Hughes
Founder





T: 07447927763
E: hello@kaiserbear.co.uk
W: www.kaiserbear.co.uk
