### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by IvanRave** [flyingsparx/NodeDirectUploader#3]
I am PUTting files to S3 via ajax requests and about 50% of the time I get ERR_CONNECTION_RESET errors.

I know the requests are signed correctly -- any ideas what may be causing this? Again, this is an intermittent problem that I see from multiple locations and machines.

http://stackoverflow.com/questions/22798774/err-connection-reset-when-putting-to-s3

**Comment by bastianwegge** [comment]
+1 on that, tried using only the s3 values on node-side to put something up and it worked, seem's like the signing or getSignedUrl doesn't work properly or we're missing something.

**Comment by radiofrequency** [comment]
+1 having same issue

**Comment by willwebberley** [comment]
Appreciate this is a very old issue now, but haven't seen this problem in a long while so assuming all fixed in later versions!
