### ISSUE TITLE
error 400 on upload

### ISSUE THREAD

**Issue by kylemcdonald** [flyingsparx/NodeDirectUploader#4]
when uploading to an s3 bucket in frankfurt, i need to add this line:

``` js
aws.config.update({ signatureVersion: 'v4', region: 'eu-central-1' });
```

inside the method that responds to `/sign_s3`.

these issues helped me figure this out:
- http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4
- https://github.com/aws/aws-sdk-ruby/issues/690

**Comment by YvesP75** [comment]
Thx!

**Comment by willwebberley** [comment]
I'm assuming this has now also been fixed generally. I also use EU buckets and the current version of the SDK seems to generate a working request!
