### ISSUE TITLE
This one does not have body-parser, 

### ISSUE THREAD

**Issue by bovetliu** [flyingsparx/NodeDirectUploader#6]
so req.body is undefined in app.post('/submit_form', function(req, res){...}

**Comment by willwebberley** [comment]
I've now removed most of the code that handles the final POST of the profile data, as this is outside the scope of the tutorial and I want to keep this companion repo as lightweight and focussed as possible. But yes - [body-parser](https://github.com/expressjs/body-parser) would be needed to handle the request
