### ISSUE TITLE
Add an example on how to get the image after upload

### ISSUE THREAD

**Issue by mebibou** [flyingsparx/NodeDirectUploader#7]
This example shows how to upload a file, but how do you display the file after upload?

**Comment by willwebberley** [comment]
The final part of the process explains how to get the URL of the image. This is the URL returned by the `/sign-s3` handler in the Node code.

Take a look at [this line](https://github.com/flyingsparx/NodeDirectUploader/blob/master/views/account.html#L39) of `account.html`, which demos setting the source of the image element to the URL of the newly-uploaded file.
